name: Scrape latest weight data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "1/20 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # Get the stamp for the eventual commit message
      - name: Get current date stamp
        run: echo "stamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Scrape Weight Data
        run: |
          deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable scrape.js

      # see docs at https://github.com/stefanzweifel/git-auto-commit-action
      - name: Commit back changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Latest weight data ${{ env.stamp }}

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: observationdata.json formatted.json

          # Optional commit user and author settings
          # commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          # commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          # commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

          # Optional. Used by `git-status`
          # See https://git-scm.com/docs/git-status#_options
          # status_options: '--untracked-files=no'
